package com.yt8492.seihekianalyzerbot

import org.springframework.boot.CommandLineRunner
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication
import org.springframework.context.annotation.Bean
import org.springframework.jdbc.core.JdbcTemplate
import org.springframework.scheduling.annotation.EnableScheduling

@SpringBootApplication
@EnableScheduling
open class SeihekianalyzerbotApplication {
    @Bean
    fun commandLineRunner(jdbcTemplate: JdbcTemplate) = CommandLineRunner {
        jdbcTemplate.execute("""CREATE TABLE IF NOT EXISTS url (
            |id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY UNIQUE,
            |url text NOT NULL UNIQUE
            |)""".trimMargin())
        jdbcTemplate.execute("""CREATE TABLE IF NOT EXISTS tag (
            |id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY UNIQUE,
            |tag text NOT NULL UNIQUE
            |)""".trimMargin())
        jdbcTemplate.execute("""CREATE TABLE IF NOT EXISTS url_tag (
            |id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY UNIQUE,
            |url_id bigint NOT NULL REFERENCES url(id),
            |tag_id bigint NOT NULL REFERENCES tag(id)
            |)""".trimMargin())
        jdbcTemplate.execute("""CREATE TABLE IF NOT EXISTS line_user (
            |id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY UNIQUE,
            |line_id text NOT NULL UNIQUE
            |)""".trimMargin())
    }
}

fun main(args: Array<String>) {
    runApplication<SeihekianalyzerbotApplication>(*args)
}
